In [80]:
import pandas as pd
import numpy as np

### Task 1 — Create Your Own DataFrame
Create a DataFrame called `students` with **at least 5 students** and these columns:
- `Name`
- `Age`
- `Subject` (their favourite subject)
- `Marks`

Use any names/values you like.

In [81]:
students = {
    "Name": ["Bilal", "Ahmed", "Ali", "Hassan"],
    "Age": [24, 26, 29, 27],
    "Subject": ["Data structures", "Networks", "Web dev", "Statistics"],
    "Marks": [82, 89, 65, 74]
}
df = pd.DataFrame(students)
df

     Name  Age          Subject  Marks
0   Bilal   24  Data structures     82
1   Ahmed   26         Networks     89
2     Ali   29          Web dev     65
3  Hassan   27       Statistics     74

### Task 2 — Explore It
Using the `students` DataFrame you just made:
1. Print the first 3 rows.
2. Print its shape.
3. Print the column names.

In [82]:
df.head(3)

    Name  Age          Subject  Marks
0  Bilal   24  Data structures     82
1  Ahmed   26         Networks     89
2    Ali   29          Web dev     65

In [83]:
df.shape

(4, 4)

In [84]:


df.columns

Index(['Name', 'Age', 'Subject', 'Marks'], dtype='object')

### Task 3 — Select Columns
Select and display only the `Name` and `Marks` columns.

In [85]:
df[["Name", "Marks"]]

     Name  Marks
0   Bilal     82
1   Ahmed     89
2     Ali     65
3  Hassan     74

### Task 4 — Filter Rows
Display only the students who scored **more than 70** marks.

In [86]:
high_scores = df[df["Marks"] > 70]
high_scores

     Name  Age          Subject  Marks
0   Bilal   24  Data structures     82
1   Ahmed   26         Networks     89
3  Hassan   27       Statistics     74

### Task 5 — Add a Column
Add a new column called `Grade`. Set it to `"A"` if Marks >= 80, otherwise `"B"`.

Hint: you can first set the whole column to `"B"`, then use `.loc` to change specific rows to `"A"` — just like we did with Bilal's city earlier.

In [87]:
df["Grade"] = "B"
df

     Name  Age          Subject  Marks Grade
0   Bilal   24  Data structures     82     B
1   Ahmed   26         Networks     89     B
2     Ali   29          Web dev     65     B
3  Hassan   27       Statistics     74     B

In [88]:
df.loc[df["Marks"] >= 80, "Grade"] = "A"
df

     Name  Age          Subject  Marks Grade
0   Bilal   24  Data structures     82     A
1   Ahmed   26         Networks     89     A
2     Ali   29          Web dev     65     B
3  Hassan   27       Statistics     74     B

### Task 6 — Sort
Sort your `students` DataFrame by `Marks`, from **highest to lowest**.

In [89]:
sort = df.sort_values("Marks", ascending=False)
sort

     Name  Age          Subject  Marks Grade
1   Ahmed   26         Networks     89     A
0   Bilal   24  Data structures     82     A
3  Hassan   27       Statistics     74     B
2     Ali   29          Web dev     65     B

### Task 7 — Handle Missing Data
1. Change one student's `Age` value to `np.nan` (missing) using `.loc`.
2. Check how many missing values are in the `Age` column.
3. Fill the missing value with the average age.

In [90]:
df.loc[df["Name"] == "Hassan", "Age"] = np.nan
df

     Name   Age          Subject  Marks Grade
0   Bilal  24.0  Data structures     82     A
1   Ahmed  26.0         Networks     89     A
2     Ali  29.0          Web dev     65     B
3  Hassan   NaN       Statistics     74     B

In [91]:
df["Age"] = df["Age"].fillna(df["Age"].mean())
df

     Name        Age          Subject  Marks Grade
0   Bilal  24.000000  Data structures     82     A
1   Ahmed  26.000000         Networks     89     A
2     Ali  29.000000          Web dev     65     B
3  Hassan  26.333333       Statistics     74     B

### Task 8 — Group and Summarize
Use `groupby` to find the **average Marks** for each `Subject`.

In [93]:
df.groupby("Subject")["Marks"].mean()

Subject
Data structures    82.0
Networks           89.0
Statistics         74.0
Web dev            65.0
Name: Marks, dtype: float64

### 🌟 Bonus Task — Save and Reload
1. Save your `students` DataFrame to a file called `my_students.csv`.
2. Read it back into a new DataFrame called `reloaded_students`.
3. Print `reloaded_students` to confirm it worked.

In [94]:
df.to_csv("my_students.csv", index=False)

In [95]:
reloaded_students = pd.read_csv("my_students.csv")
reloaded_students

     Name        Age          Subject  Marks Grade
0   Bilal  24.000000  Data structures     82     A
1   Ahmed  26.000000         Networks     89     A
2     Ali  29.000000          Web dev     65     B
3  Hassan  26.333333       Statistics     74     B